name: NuGet for Md.Crypto
on:
  push:
    paths:
      - Md.Crypto/Md.Crypto/**
      - .github/workflows/Md.Crypto.yaml
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
  packages: write
  pages: write
jobs:
  create-nuget-code-coverage-page:
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-nuget-code-coverage-page.yaml@main
    with:
      project-name: Md.Crypto
      solution-directory: Md.Crypto
      test-project-name: Md.Crypto.Test
